node {
    def myGradleContainer = docker.image('gradle:jdk8-alpine')
    myGradleContainer.pull()

    stage('Preparación') {
        git branch: 'main', url: 'https://github.com/macloujulian/gs-gradle.git'
    }

    stage('Construcción') {
      // Se asigna memoria y ulimit
      myGradleContainer.inside("-v ${env.HOME}/.gradle:/home/gradle/.gradle --memory=2g --memory-swap=2g --ulimit nofile=65535:65535") {
        // Limitar memoria JVM de Gradle
        sh '''
          cd complete
          echo "org.gradle.jvmargs=-Xmx512m -Dfile.encoding=UTF-8" > gradle.properties
          /opt/gradle/bin/gradle build
        '''
      }
    }

    stage('Sonar Scanner') {
      def sonarqubeScannerHome = tool name: 'sonar', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
      withCredentials([string(credentialsId: 'sonar', variable: 'sonarLogin')]) {
        sh "${sonarqubeScannerHome}/bin/sonar-scanner -e -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=${sonarLogin} -Dsonar.projectName=gs-gradle -Dsonar.projectVersion=${env.BUILD_NUMBER} -Dsonar.projectKey=GS -Dsonar.sources=complete/src/main/ -Dsonar.tests=complete/src/test/ -Dsonar.language=java -Dsonar.java.binaries=."
      }
    }
}
